### ISSUE TITLE
Abbreviation markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/BEN#2]
Only a few of the Cologne dictionaries have added markup for abbreviations.  
I think adding such markup would be a useful addition to any dictionary; such markup, along with an accompanying tooltip file, allows tooltips for the abbreviations in displays, which is a benefit to users.

Benfey has a nice list of abbreviations, which Thomas digitized.
* [Cologne front matter for Benfey](https://sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/benpref.html#contractions-and-signs)
* Corresponding [Scanned images](https://archive.org/details/sanskritenglishd00benf/page/n11/mode/2up).

Will work with @sanskritisampada to accomplish this for Benfey.

If others agree this is useful to proceed with now for other dictionaries,  will do so.

**Comment by funderburkjim** [comment]
[ben_abwork.txt](https://github.com/sanskrit-lexicon/BEN/blob/master/abbrev/ben_abwork.txt) contains the
text of the abbreviations as extracted from the digitization ben.txt in csl-orig repository.

[ben_abwork_edit.txt](https://github.com/sanskrit-lexicon/BEN/blob/master/abbrev/ben_abwork_edit.txt) contains the edited version prepared by @sanskritisampada, including these proofreading corrections:

```
Sam corrections:

Old: Aufr. Ujjvalad. = Ujjvaladatta, ed. Autrect.
New: Aufr. Ujjvalad. = Ujjvaladatta, ed. Aufrect.

Old: Böhtl. Ind. Spr. = Böhtlingk. Indische Spr{??}ce (Indian Sentences).
New: Böhtl. Ind. Spr. = Böhtlingk. Indische Sprüche (Indian Sentences).

Old: Śṛṅgārat. = Śṛṅgāratilaks, ed. Gildemeister, in his edition of the Meghadūta.
New: Śṛṅgārat. = Śṛṅgāratilaka, ed. Gildemeister, in his edition of the Meghadūta.

Old: Ghaṭ. = Ghaṭakarpara, ed. Cale.
New: Ghaṭ. = Ghaṭakarpara, ed. Calc.

Old: Gött. Gel. Anz. = Göttinger Gelebrte Anzeigen, i. e. ‘Scientific Reports published in Göttingen.’
New: Gött. Gel. Anz. = Göttinger Gelehrte Anzeigen, i. e. ‘Scientific Reports published in Göttingen.’

Old: Nalod. = Nalodya, ed. Benary.
New: Nalod. = Nalodaya, ed. Benary.

Old: Ragh. = Raghuvaffiśa, ed. Stenzler.
New: Ragh. = Raghuvaṃśa, ed. Stenzler.

Old: Web. Ind. St. = Weber, Indische Studien, i. e. ‘Essaya concerning India.’
New: Web. Ind. St. = Weber, Indische Studien, i. e. ‘Essays concerning India.’

Old: Yogas. = Yogasūtrāṇi, ed. Allahabed, 1852-53.
New: Yogas. = Yogasūtrāṇi, ed. Allahabad, 1852-53.

```

**Comment by funderburkjim** [comment]
## separation into 'ab' and 'ls'

Both 'common abbreviations'  (e.g. `Ātm. = Ātmanepada.`) and literary source abbreviations (e.g. `Amar. = Amaruśataka, ed. Calcutt.`) are in the list.

In the Cologne digitizations, these are distinguished with different markups `<ab>` and `<ls>`.

Thus, separating ben_abwork_edit.txt (125 lines) into two parts:
* [ben_ab.txt](https://github.com/sanskrit-lexicon/BEN/blob/master/abbrev/ben_ab.txt)  (25 lines)
* [ben_ls.txt](https://github.com/sanskrit-lexicon/BEN/blob/master/abbrev/ben_ls.txt)   (108 lines)
  * some of these have two versions of the abbreviation, e.g. `Brāhmaṇ. and Brāhmaṇav. = Brāhmaṇavilāpa`, and generate two abbreviations

Here is one that generates 5 lines in ben_ls.txt
```
Häb. and Häberl. Chr. or Anth. = Kāvya Sangraha, ‘A Sanskrit Anthology,’ by John Häberlin.

Häb. = Kāvya Sangraha, ‘A Sanskrit Anthology,’ by John Häberlin.
Häberl. = Kāvya Sangraha, ‘A Sanskrit Anthology,’ by John Häberlin.
Häberl. Chr. = Kāvya Sangraha, ‘A Sanskrit Anthology,’ by John Häberlin.
Häberl. Anth. = Kāvya Sangraha, ‘A Sanskrit Anthology,’ by John Häberlin.
Häberl. Anthol. = Kāvya Sangraha, ‘A Sanskrit Anthology,’ by John Häberlin.
```

**Comment by funderburkjim** [comment]
## long tooltips

A few abbreviations contain guidance for interpretation of the abbreviation.  
```
Hit. = Hitopadeśa, ed. of Lassen, and when followed by M.M.,that of Max Müller. When followed by two Arabian numerals, the first denotes the page, the second the line; when followed by a Roman and Arabian numeral, the first denotes the book, the second the distich.

Man. = Mānavadharmaśāstra, ed. Haughton and Lois. (i. e. Loiseleur Deslongchamps). Where there is a numeral in brackets, it denotes the verse of Jones’ translation.

Nal. = Nala, an episode of the MBh. ed. Bopp.; a numeral in brackets denotes Böhtlingk's ed. in his Chrestomathy.


Pañc. = Pañcatantra, ed. Kosegarten; the numerals are used on the same system as in Hit. When there is added ‘ed. orn.,’ it denotes the fragment of the recensioornatior, published by Kosegarten.

Rām. = Rāmāyaṇa, the two first books after the ed. of Schlegel; when that of Gorresio is meant, there is added Gorr.; the remaining books after Gorresio's.

Suśr. = Suśruta, ed. Calc.; the first numeral denotes the vol., the second the page, the third the line.

```

These full abbreviation expansions will be awkward when viewed as html tooltips in the displays.

**Comment by funderburkjim** [comment]
`Vārt. = Vārtika.`  is counted as a 'literary source'

**Comment by funderburkjim** [comment]
##  Capitalized abbreviations

For a few common abbreviations, the abbreviation is given originally in ben.txt with an initial lower-case letter,'
but also the capitalized form of the abbreviation is found in the text.
```
30 instances of capitalized Frequent.
15 instances of capitalized Desid.
76 instances of capitalized D.
```

We add 'Desid.' and 'Frequent.' to ben_ab.txt.

However, 'D.' is NOT added -  all the instances are part of the literary source `Sāh. D.`.


## comment on 'd.'
This is abbreviation for 'distich' (*a pair of verse lines; a couplet.*).  
This occur 4000+ times, within the details of various literary sources, for example:
```
{#aDijya#}¦ {%adhi-jya%} (cf. {%jyā%}), adj.
<div n="lb">Strung (as a bow), Śāk. <ab>d.</ab> 6.
```
And aDijya can be found in verse 6 in Lanman's edition at https://archive.org/details/in.ernet.dli.2015.485675/page/n19/mode/2up
![image](https://user-images.githubusercontent.com/6393033/132147255-390fb407-e89d-41b9-9316-c04736f64ebb.png)

**Comment by funderburkjim** [comment]
## 2 print changes
Sāh. D. = Sāhitya Darpaṇa, in Bibliotheca Indica.

Two instances as 'Sāh. d.':
```
under hw puz, L=9029
Sāh. d. 7, 19. {%Anya-,%} m. the Indian

under hw vaYjula, L=12612
Sāh. d. 19, 19. {@2.@} A sort of bird.
```

Both changed to 'Sāh. D.' and noted as print changes.

**Comment by funderburkjim** [comment]
## Aufr. Ujjvalad.
In the frontmatter, we have 
`Aufr. Ujjvalad. = Ujjvaladatta, ed. Aufrect.`

The 4 instances appear as 'Aufrecht, Ujjvalad.'

Changed abbreviation tooltip to
`Ujjvalad. = Ujjvaladatta, ed. Aufrecht.`

Also correction to spelling `Aufrecht`.

**Comment by funderburkjim** [comment]
## Govardh. Āryas. 
Tooltip from frontmatter = `Govardh. Āryas. = Govardhana Āryasaptati, ed. Soma Nath Mookerjea.`

This occurs 3 times, but in slightly different forms:
```
or birds, Govardhana, Āryā Sapt. 154,
an elephant, Govardh. Āryā Sapt.
earth, Govardh. Āryā Saptaśatī, 163, d.
```
Several changes to tooltips
* `Āryasaptati` changed to `Āryāsaptaśatī`  (cf. MW) in tooltip
* and three variants of tooltip *abbreviation*:
   * Govardhana, Āryā Sapt.
   * Govardh. Āryā Sapt.
   * Govardh. Āryā Saptaśatī,

**Comment by funderburkjim** [comment]
## Śārṅg.
Tooltip `Śārṅg. Paddh. = Śārṅgadhara-Paddhati (MSS. used by Böhtl.).`
`Śārṅg.` occurs only once in text.
Thus change tooltip to
`Śārṅg. = Śārṅgadhara-Paddhati (MSS. used by Böhtl.).`

## Somadev. Nal. 
Tooltip: `Somadev. Nal. = Somadeva's Nala, published by Brockhaus.`

There is no 'Somadev' in the text.
There is also a Nal. tip:
`Nal. = Nala, an episode of the MBh. ed. Bopp.; a numeral in brackets denotes Böhtlingk's ed. in his Chrestomathy.`

Remove `Somadev. Nal. ` from the ls tooltip file, as it is unused.

**Comment by funderburkjim** [comment]
## Ind. St.
Tooltip: `Web. Ind. St. = Weber, Indische Studien, i. e. ‘Essays concerning India.’`

This particular form of the abbreviation does not occur.
Most seem to be of form 'Weber, Ind. St.'.

Change tooltip abbreviation to 'Ind. St.' 
`Ind. St. = Weber, Indische Studien, i. e. ‘Essays concerning India.’`

**Comment by funderburkjim** [comment]
## Sāṅkhya Aph.
Tooltip: `Sāṅkhya Aph. = Sāṅkhya Sūtras, in Hall's ed. of Saṅkhya Pravacana Bhāṣya in Bibl. Ind.`

The spelling occurs in text with `dental nasal 'n'` (2 instances)
Change text from `Sānkhya` to `Sāṅkhya`, and note as print changes.
```
L=4980 : cit (2nd homonym) : Sānkhya Aph.  : Sāṅkhya Aph.
L=15950: sAMsidDika :  Sāukhya Aph. : Sāṅkhya Aph.
```

**Comment by funderburkjim** [comment]
## Lass. Pent.
Tooltip: `Lass. Pent. = Lassen, Commentatio de Pentapotamia Indica.`

This abbreviation doe not occur, but the abbreviation `Lass. Pentap.`  occurs 7 times.

Change tooltip abbreviation to `Lass. Pentap.`

**Comment by funderburkjim** [comment]
## Nyāy. S.
Tooltip `Nyāy. S. = Nyāya-Sūtrāṇi of Gotama, ed. Calc.`

Abbreviation `Nyāy. S.` does not occur, but
once `Nyāya S.` occurs, split on two lines, under padArTa L=8071.
```
OLD:
<div n="lb">m. {@1.@} The meaning of a word, Nyāya
<div n="lb">S. 2, 131. {@2.@} Substance, thing, Bhāg.
NEW:
<div n="lb">m. {@1.@} The meaning of a word, 
<div n="lb">Nyāya S. 2, 131. {@2.@} Substance, thing, Bhāg.
<div n="lb">P. 3, 11, 2. {@3.@} A category, Bhāṣāp. 1.
```
Change tooltip abbreviation to `Nyāya S. `

There are other examples where 2-word LS abbreviations are split on 2 lines.
These will be examined in another step, and the lines changed so abbreviation on one line.

**Comment by funderburkjim** [comment]
## Śrutab.
Tooltip: `Śrutab. = Śrutabodha, ed. Brockhaus.`

Abbreviation `Śrutab.` does not occur.
It was, in the front matter, given as `Śrut. and Śrutab. = Śrutabodha`.
and there are 20 `Śrut.` abbreviations in text. 

Remove `Śrutab.` abbreviation tooltip, since unused.

**Comment by funderburkjim** [comment]
## Mahāv.
Tooltip `Mahāv. = Mahāvīracarita, ed. Trithen.`

The abbreviation appears in several forms:
```
Mahāv. 10
Mahāvīrac. 6
Mahāvīr. 1
```
Add the abbreviations Mahāvīrac. and Mahāvīr to ben_ls.txt

**Comment by gasyoun** [comment]
> If others agree this is useful to proceed with now for other dictionaries, will do so.

Sure we do. Only the major dictionaries will be left without love for a few months, otherwise fully agree. Thanks for all the attention to details!

recensioornatior -> recensio ornatior

**Comment by funderburkjim** [comment]
Several minor changes to ben.txt were felt necessary in preparation for the ab, ls markup.
See [this commit of ben.txt](https://github.com/sanskrit-lexicon/csl-orig/commit/910836731d520c980f8a78dd1d95543df111c10e),

**Comment by Andhrabharati** [comment]
> If others agree this is useful to proceed with now for other dictionaries, will do so.

This must be a std. feature to be done in all dictionaries, whether listed or not in the resp. book.

And the exercise should consider all the inside occurances, even if undocumented in the book for whatever reason.

I see some of them still lying untouched (unnoticed) even in MW, inspite of it being worked for over 20 years now.

**Comment by gasyoun** [comment]
> I see some of them still lying untouched (unnoticed) even in MW, inspite of it being worked for over 20 years now.

Yes, sure they are. Nobody has ever dived as deep as you would want to.

**Comment by funderburkjim** [comment]
## Work concluded.
See readme.md for the [abbrev directory](https://github.com/sanskrit-lexicon/BEN/tree/master/abbrev) for description of interesting files.

The 'stat' files will probably have general interest. From those, we note
* 14970 common abbreviation markup instances, using front-matter common abbreviations
* 50970 common abbreviations using observed abbreviations not appearing in front matter listing
* 48713 literary source abbreviations, based almost entirely on front matter, but with a few variations and
  additions.

**Comment by funderburkjim** [comment]
## display tooltips

Several steps are required so that the markup generates tooltips in the displays.
This involves changes in repositories:
* [csl-pywork](https://github.com/sanskrit-lexicon/csl-pywork/commit/ac963e356bb1eb248dd4810ebb6ee8cf1588a39a) so sqlite tooltip files will be generated
  for 'ab' abreviations and for 'ls'  abbreviations
* [csl-apidev](https://github.com/sanskrit-lexicon/csl-apidev/commit/11394fc18a3c60724a427a7addbb029244382160)   So simple search and related displays use the sqlite file when html is generated
* [csl-websanlexicon](https://github.com/sanskrit-lexicon/csl-websanlexicon/commit/6a98c1ff6f07912d22cb7331ebbc8b47ccc7c04d) So basic  related displays use the sqlite file when html is generated

**Comment by gasyoun** [comment]
> See readme.md for the abbrev directory for description of interesting files.

BEN can he happy.

**Comment by funderburkjim** [comment]
@Andhrabharati 
If you notice particular missed abbreviation markup in MW, please open an issue and mention the details, so improvements in markup can be made.

**Comment by funderburkjim** [comment]
> This must be a std. feature  ....

Agree with the sentiment.
