### ISSUE TITLE
Addl. strings for ab, ls and bot markings

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/BEN#3]
@drdhaval2785 & @funderburkjim 
I've seen somewhere the workout for ab & ls markings in BEN recently.

There are some more candidates remaining still unmarked, either proper or due to typo/conversion errors,
**Some of these are independent and some go as a set with other adjacent words.**

Here is the extract for study and necessary action.
[ben abbr_ls hunt.txt](https://github.com/sanskrit-lexicon/BEN/files/7191089/ben.abbr_ls.hunt.txt)

**Comment by gasyoun** [comment]
> Here is the extract for study and necessary action

You want these 238 to be added some markup? But we still do not know what all of them stand for.

**Comment by Andhrabharati** [comment]
First the typos etc. need to be corrected.
[These can be found by searching with regex `[^>]` (i.e. un-tagged) preceding those listed in my file.]

May be a job for Sampada?

**Comment by Andhrabharati** [comment]
As this ab & ls hunting work is done more rigorously elsewhere (by me), closing this now.
