### ISSUE TITLE
Greek text

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/BEN#6]
This issue devoted to mining the Greek text for Benfey dictionaries
from the version prepared by @Andhrabharati  ([reference](https://github.com/sanskrit-lexicon/csl-devanagari/issues/32#issuecomment-1115115483)).

**Comment by funderburkjim** [comment]
## Greek text added
Work done in [greek](https://github.com/sanskrit-lexicon/BEN/tree/master/greek) directory.
The method used was to transfer the greek text fragments from Andhrabharati's BEN_main_L2a.txt file (see link above) into the bur.txt digitization of csl-orig/v02/bur.
First we require a few adjustments so that the list of entries in the CSL and AB versions are the same.
Then for each corresponding entry, we require that the number of `<lang n="greek">.*?</lang>` patterns be the same.  This requirement is not initially met for various reasons,  the main reason being how greek text  spanning a line break is marked with two lang fragments in CSL, but one only in AB.  This is generally resolved by removing a lang element in CSL version.  After several adjustments, this requirement is met.
Then, for a given entry,  we align the N greek text fragments from CSL and AB, and replace the first Greek text fragment in CSL with the first greek text fragment in AB,  and similarly for the 2nd, 3rd, ... ,, Nth fragments.
When this is done for all the entries, then the transfer is considered to be complete.
And in both CSL and AB versions we have 1243 greek text fragments.

**Comment by funderburkjim** [comment]
@Andhrabharati 
There was one entry (L=14998) where I think your version had a small missing text fragment.
I attempted to add the greek text as κρανρος  but think the ν is wrong.   Please review (use change_ab_3.txt to see exactly the change ), and make a comment below for the correction to κρανρος , which I will then enter separately into csl-orig/v02/ben/ben.txt.

**Comment by funderburkjim** [comment]
## proof reading
[proof_greek.txt](https://github.com/sanskrit-lexicon/BEN/blob/master/greek/proof_greek.txt) was prepared to help someone proof read the greek text.  
This listing could be used along with the scan-page display url:
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ben&page=969.

Note the page is given in the `<pc>` element in proof_greek.

Perhaps @jmigliori could undertake this proof-reading task when his time permits?

**Comment by Andhrabharati** [comment]
Here is the replacement text--
κρανρος > κραῦρος

**Comment by Andhrabharati** [comment]
(change_ab_3.txt) line 73:
ἄχνυμαι ἄχος > ἄχνυμαι, ἄχος
(comma missing in the beginning portion)

**Comment by funderburkjim** [comment]
two items above adjusted.
I think we can close this now.  Will open separate issue for proof-reading, in hopes that @jmigliori or someone else undertakes that.

**Comment by funderburkjim** [comment]
## punctuation

In [ref](https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/20#issuecomment-1133660605), @Andhrabharati observes

> more often than not, the punctuation mark (mostly , and ;) are missed after the ending Greek tag.

This comment is applicable to the Benfey greek text.   
Was able to find a way to add the punctuation (from AB version) to the ben.txt file.
This has been done.  
About 750 lines changed.
One way to examine the changes is in the diff file for revised proof_greek.txt ([see](https://github.com/sanskrit-lexicon/BEN/commit/5758520fb098222c27df704cdf57839d27036f8d#diff-144818f9ea84900eceea11b1357de0b97f61104fac24baeec35f1505965331e2)).

Or, the change file : [change_7.txt](https://github.com/sanskrit-lexicon/BEN/blob/master/greek/change_7.txt)
Will investigate similar punctuation revision for recent greek text additions to bop and bur dictionaries.

**Comment by Andhrabharati** [comment]
Probably the csl INM file also needs this punctuation 'revisit' for the Greek strings. (I haven't seen Jim's file so far.)

**Comment by funderburkjim** [comment]
## greek text in addenda section
This  from ben_Addenda.txt file provided by @Andhrabharati  ([reference](https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/36#issuecomment-1136264247)).
