### ISSUE TITLE
Greek text proofreading

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/BEN#8]
As mentioned in #6, a document proof_greek.txt is prepared for proofreading the Greek text.
This issue opened for discussion of that step.

**Comment by drdhaval2785** [comment]
Any update here @funderburkjim ?
@jmigliori is interested to proofread this?

**Comment by funderburkjim** [comment]
@jmigliori are you there? Jonathan, Do you foresee having time to proofread?

**Comment by jmigliori** [comment]
How many Greek entries are there to be proofread? I do have some free time,
but I can’t take on any major projects right now I’m afraid.

**Comment by funderburkjim** [comment]
Hi, Jonathan.  I count slightly less than 1300 instances of Greek text in Benfey.
You can see the text by
* https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/ben/ben.txt
* Right click "Save link as"  on 'view raw'

**Comment by funderburkjim** [comment]
The Greek text fragments are identified by `<lang n="greek">XXX</lang>`

**Comment by jmigliori** [comment]
I'm a little rusty: is there a faster way for me to access the page scans
than going to
https://www.sanskrit-lexicon.uni-koeln.de/scans/BENScan/2020/web/webtc2/index.php
and pasting the headwords in?

**Comment by funderburkjim** [comment]
@jmigliori   
Here's a convenient way to get the scanned images
First instance of \<lang n="greek"> occurs in ben.txt
```
<L>4<pc>0001-a<k1>aMSu<k2>aMSu
....
<ab>Cf.</ab> <lang n="greek">ἀκτίν</lang>.
```
Note `\<pc>0001-a\`    This means page 1.

Now here is url for image of page 1 in Benfey:
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ben&page=1

Here's another example
```
<L>3733<pc>0213-a<k1>kfmi<k2>kfmi
... 
vaurms; <lang n="greek">ἕλμινς</lang>.
```
Just edit the page= parameter in the browser address from '1' to '213'

https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ben&page=213

So replacing the page= number with the page number from `<pc>...`   

Hope you find this more convenient.

**Comment by jmigliori** [comment]
I finished reviewing ben.txt and found no corrections to make. Bravo!

**Comment by Andhrabharati** [comment]
That's good to know, @jmigliori !!

BTW, I am now completely reviewing the Monier Willaims 1899 ed. and found quite a few errors in Greek terms therein, incl. spelling errors-- (mostly φ for ϕ) and even some missings!

I guess the reason for the **missings** as **checking just the tagged lists** earlier, instead of looking at the full print lines.

Probably you might be interested to see those as well, if time permits.

@funderburkjim , shall I post all those etym lines, incl. greek, for you to handle them all at once (like in Bopp and Benfey)?

**Comment by funderburkjim** [comment]
@jmigliori   Wow! Thanks Jonathan!  
And congratulations to @Andhrabharati for his amazing accuracy in the Benfey Greek text.

**Comment by funderburkjim** [comment]
@Andhrabharati 
  Regarding` the MW Greek.  There appear to be two aspects 
* proof-reading of text already marked as greek  (about 1100 of these in mw)
   * I can prepare an extraction from cdsl mw.txt that @AnnaRybakovaT or @jmigliori can use to proof.  Will do this extraction at time of proofing
* 'missed' Greek.   Will need to depend on @Andhrabharati for a list of these
   missing items.

**Comment by gasyoun** [comment]
>'missed' Greek.

Hope @Andhrabharati has some good catches

**Comment by Andhrabharati** [comment]
Not that many missings @gasyoun , but quite some errors are found!!

**Comment by funderburkjim** [comment]
@AnnaRybakovaT 

Review of Benfey Greek text will be next on your agenda (after [BOP Greek text proofreading](https://github.com/sanskrit-lexicon/BOP/issues/4)).
[This comment](https://github.com/sanskrit-lexicon/BUR/issues/4#issuecomment-1482631476) and the associated file 'ben_Addenda_changes.txt' should be consulted at the time of the Benfey Greek text proofreading.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT 

Benfey Greek Text Proofreading startup instructions are [here](https://github.com/sanskrit-lexicon/BEN/tree/master/issues/issue8).

Please see the notes at  comment of 'Mar 24' above, and consult with @Andhrabharati as needed.

**Comment by Andhrabharati** [comment]
@funderburkjim 

There is no need for checking Slav. (just a single word present, that too in Roman letters) and Russ. words (NIL) in BEN.

It seems you took the Bopp readme.txt as the "base" for Benfey also!!

**Comment by funderburkjim** [comment]
Oops!  Yes -- the Ben readme was adapted from the Bopp readme.  Ben readme now revised.

**Comment by AnnaRybakovaT** [comment]
> Ben readme now revised

Dear all,
I am here again)))
So I am ready to do this task. As I see - there is nothing special, just proofreading only Greek text  similar to the previous tasks.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT   Hi!  Yes, AFAIK (as far as I know)  task for you is proofreading the Greek text in Benfey. 
Also please check [this comment above](https://github.com/sanskrit-lexicon/BEN/issues/8#issuecomment-1483051063) .
   and check file ben_Addenda_changes.txt  prepared by @Andhrabharati .

Also see instructions at https://github.com/sanskrit-lexicon/BEN/tree/master/issues/issue8.

**Comment by AnnaRybakovaT** [comment]
> Also please check [this comment above](https://github.com/sanskrit-lexicon/BEN/issues/8#issuecomment-1483051063) .
> and check file ben_Addenda_changes.txt prepared by @Andhrabharati .

ok)))

**Comment by AnnaRybakovaT** [comment]
> Yes, AFAIK (as far as I know) task for you is proofreading the Greek text in Benfey.
> Also please check [this comment above](https://github.com/sanskrit-lexicon/BEN/issues/8#issuecomment-1483051063) .
> and check file ben_Addenda_changes.txt prepared by @Andhrabharati .

Dear all,
change_1.txt is ready.

please, check some lines, since I am not sure:

39485 line  - παπταίνω
![изображение](https://github.com/sanskrit-lexicon/BEN/assets/74726889/5579e1fa-02c8-4e08-93a3-6e8167cb1e69)

50411 line - Commas
![изображение](https://github.com/sanskrit-lexicon/BEN/assets/74726889/2d6e453d-d962-4682-adea-9aaaebcd2981)

54615 line  - {%dāva,%}
![изображение](https://github.com/sanskrit-lexicon/BEN/assets/74726889/534f4fdc-2d44-4a9a-be53-166dd09ce9b0)

If I don't answer fast, please, wait for some days. Now my main seasonal work has start and I don't have much free time.

**Comment by Andhrabharati** [comment]
@AnnaRybakovaT 

39458 line - παπταίνω [;;note the line number]
pl. see the google result from https://greek_russian.academic.ru/47180/%CF%80%CE%B1%CF%80%CF%84%CE%B1%CE%B9%CE%BD%CF%89

![image](https://github.com/sanskrit-lexicon/BEN/assets/75209130/ae63be78-6fcd-4f2f-868d-887a29630b1b)


50411 line -
Though the print has no commas at these, I thought they should've been there (taking that these individual words are to be referred to);  I may be wrong.

@jmigliori 
can you help reg. this?

line 54615 -

this has to be {%dā̆va%}, i.e. dăva (dava) or dāva

**Comment by AnnaRybakovaT** [comment]
> 39458 line - παπταίνω [;;note the line number]

I suppose - should be just 
παπταίνω

**Comment by jmigliori** [comment]
Hi, sorry for the delayed response. I agree that 39458 is παπταίνω: that’s
a diphthong in the middle and can’t be a diaresis. I also agree that there
should be commas in 50411.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Now, it's your turn to take over!

**Comment by funderburkjim** [comment]
## change_1 installed

**Comment by funderburkjim** [comment]
## change_2
The change `dā̆va` at line 54615 now made.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT   Thanks for the changes!

Is there a pending 'next task' for you that we need to arrange?

**Comment by Andhrabharati** [comment]
> @AnnaRybakovaT Thanks for the changes!
> 
> Is there a pending 'next task' for you that we need to arrange?

Why not take [this](https://github.com/sanskrit-lexicon/csl-orig/issues/695#issuecomment-1000453762) up as the 'next task', @funderburkjim / @AnnaRybakovaT ?

**Comment by funderburkjim** [comment]
@Andhrabharati   Yes - preparing an abbreviation tooltip file for MD would be a good task.
